### ISSUE TITLE
Homebridge Crashes with nes

### ISSUE THREAD

**Issue by Slepperpon** [KraigM/homebridge-nest#3] opened 2015-11-23 17:53 UTC
With just nest and smartthings running it crashes with nest i think.
also if i try and add harmony will not start now i do have to harmony hubs in the house if that makes a difference.

**Comment by KraigM** [comment] 2015-12-07 01:15
That is one problem with splitting everything on HomeBridge up into separate pieces, how do you post  cross plugin issues lol.  

SmartThings is not me so if he is the culprit, can't help you there.  

As far as the Nest crashing, can you post the logs.

As far as Harmony Hub, I do manage that one on https://github.com/KraigM/homebridge-harmonyhub so you can post the harmony issue over there.  But quickly, if you have multiple harmony hubs on the same network see https://github.com/KraigM/homebridge-harmonyhub/issues/5

**Comment by Slepperpon** [comment] 2015-12-11 18:42
[Nest] Target temperature for Nest02AA01AC401303D8 is: 21.11111111111111undefined:1<html>redirect to <a href="https://czfe15-front01-iad01.transport.home.nest.com/v2/subscribe">https://czfe15-front01-iad01.transport.home.nest.com/v2/subscribe</html>^
SyntaxError: Unexpected token <    at Object.parse (native)    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/unofficial-nest-api/index.js:167:40)    at emitNone (events.js:72:20)    at IncomingMessage.emit (events.js:166:7)    at endReadableNT (_stream_readable.js:893:12)    at doNTCallback2 (node.js:429:9)    at process._tickCallback (node.js:343:17)

This is the error i get with nest.If i run without nest platform homebridge runs with no problem
Date: Sun, 6 Dec 2015 17:15:16 -0800

**Comment by KraigM** [comment] 2015-12-12 01:05
This has been written up already as an occasional issue (#4).  Is it an occasional issue for you too or does yours crash immediately?

**Comment by KraigM** [comment] 2015-12-14 03:16
Appears to be duplicate of #4 so Im going to close it

**Closed by KraigM** 2015-12-14 03:16 UTC
Labels: duplicate
