### ISSUE TITLE
Firebase warning appeared after a few days with the new API

### ISSUE THREAD

**Issue by ande2965** [KraigM/homebridge-nest#23] opened 2016-01-05 13:12 UTC
The new API has been working great, but then this warning appeared yesterday and I couldn't communicate with the Nest until I restarted homebridge:

"FIREBASE WARNING: auth() was canceled: {"error":"service unavailable","type":"https://developer.nest.com/documentation/cloud/error-messages#service-unavailable","message":"service unavailable","instance":"489e16b1-3289-40c1-9e56-d6d6057bcadc"}"

**Comment by pacific707** [comment] 2016-01-07 01:04
I also have had the same problem

**Comment by KraigM** [comment] 2016-01-09 02:51
Not sure on that one.  This was my first experience with firebase, so I may have missed something.

**Comment by KraigM** [comment] 2016-01-09 02:52
i.e. some error handling, reconnection handling, or something

**Comment by jbolter** [comment] 2016-01-18 06:19
I had the same problem today.  Had to restart Homebridge to get the Nest communication working again.

**Comment by KraigM** [comment] 2016-01-23 15:42
Closing this due to lack of info.  Feel free to provide more info and reopen

**Comment by jbolter** [comment] 2016-01-25 19:10
The issue is definitely with error handling...what info can we provide?  My error in the console was related to firebase and directed me to this URL:

https://developer.nest.com/documentation/cloud/error-messages#service-unavailable

There it says to check the Nest service status and there were some issues related to the API availability.  Seems like if the homebridge-nest app fails to connect to the Nest service then it just throws an error and is never able to reconnect until homebridge is restarted.

**Comment by jbolter** [comment] 2016-01-25 19:13
I think you'll have to re-open the issue as I don't seem to have permissions.

**Comment by ande2965** [comment] 2016-01-25 19:13
I would second jbolter on what information would be helpful? I continue to see this error appear every few days, and the only solution seems to be killing home bridge and starting it again.

**Comment by KraigM** [comment] 2016-01-26 05:19
This happens after it has been running for awhile successfully, yes?

**Comment by ande2965** [comment] 2016-01-26 05:31
Yes, it runs continuously and without issue for a few days, and then this error appears and it stops working. When that happens, I can kill homebridge and launch it again. It immediately starts up successfully and works without issue for a few more days before the error happens again with the same result.

**Comment by KraigM** [comment] 2016-01-26 05:32
From what I understand, firebase is built to black box reconnect automatically.  The auth call that it seems to be referring to is the one that is used on the initial connect, but that is the only time this plugin calls any kind of auth method.  So if auth is failing after you have been running for awhile, then I can only guess that its the auto reconnect system that is failing.  

I'm guessing this is partially related to how Nest is using Firebase.  Under normal circumstances, Im assuming Firebase is not expecting to fail auth on the reconnect (unless your access was revoked or something).  But Im guessing if Nest servers go down, then they are just denying access (because they cannot confirm access since they are down).  Firebase must just cancel any further reconnect attempts since "auth failed".

Assuming all of the above, the trick is to figure out how nest is expecting us to handle this.  Since I can't find any info on that and it is not happening to me, I'm going to have to just setup a bunch of logging and get you guys to try it out and see what logs you get.  Flying blind over here :stuck_out_tongue_winking_eye:

**Comment by KraigM** [comment] 2016-01-26 06:09
Ok I found some weird firebase things.  For one, it looks like if you disconnect, they notify that data has changed but pass null. Not sure if that will cause issues since I wasn't expecting that but Im logging that now.  Im also logging auth changes.  Can you guys try it out please
```
npm install -g git+https://github.com/KraigM/homebridge-nest.git#f6116d0f87ccabe5cc220a37b323259f651dc6a3
```

**Comment by ande2965** [comment] 2016-01-26 12:48
I installed the version you referenced but it gave me the error "ReferenceError: conn is not defined" at startup and didn't find any Nest devices. When I switched back to the regular version it didn't give the same error. Here's the output at startup for both cases:

-----------------------------------------------------------------------------------------------------

$ sudo npm install -g git+https://github.com/KraigM/homebridge-nest.git#f6116d0f87ccabe5cc220a37b323259f651dc6a3 continuation-local-storage
/usr/local/lib
├── continuation-local-storage@3.1.4 
└─┬ homebridge-nest@1.0.1  (git+https://github.com/KraigM/homebridge-nest.git#f6116d0f87ccabe5cc220a37b323259f651dc6a3)
  └── unofficial-nest-api@0.1.4  (git+https://github.com/kraigm/unofficial_nodejs_nest.git#3cbd337adc32fab3b481659b38d86f9fcd6a9c02)
$ homebridge
Loaded plugin: homebridge-nest
Registering platform 'homebridge-nest.Nest'
---
Loaded config.json with 0 accessories and 1 platforms.
---
Loading 1 platforms...
[Nest Thermostat] Initializing Nest platform...
[Nest Thermostat] Fetching Nest devices.
[Nest Thermostat] [ReferenceError: conn is not defined]
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:                   
<snip>                
Homebridge is running on port 51829.

-----------------------------------------------------------------------------------------------------

And here's the output when I reverted back to the normal version:

$ sudo npm install -g homebridge-nest continuation-local-storage
/usr/local/lib
├── continuation-local-storage@3.1.4 
└─┬ homebridge-nest@1.0.1 
  └── unofficial-nest-api@0.1.4  (git+https://github.com/kraigm/unofficial_nodejs_nest.git#3cbd337adc32fab3b481659b38d86f9fcd6a9c02)
$ homebridge
Loaded plugin: homebridge-nest
Registering platform 'homebridge-nest.Nest'
---
Loaded config.json with 0 accessories and 1 platforms.
---
Loading 1 platforms...
[Nest Thermostat] Initializing Nest platform...
[Nest Thermostat] Fetching Nest devices.
[Nest Thermostat] Temperature unit for Upstairs is: Fahrenheit
[Nest Thermostat] Current temperature for Upstairs is: 70 F
[Nest Thermostat] Current humidity for Upstairs is: 30%
[Nest Thermostat] Target temperature for Upstairs is: 70 F
[Nest Thermostat] Target heating for Upstairs is: Heating
[Nest Thermostat] Away for Upstairs is: false
[Nest Thermostat] Initializing platform accessory 'Upstairs'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
<snip>
Homebridge is running on port 51829.

**Comment by KraigM** [comment] 2016-01-26 20:49
Sorry my bad. try:
```
npm install -g git+https://github.com/KraigM/homebridge-nest.git#1dbe213cad45d11782ff4870d7c2dc8b0aed6d9e
```

**Comment by ande2965** [comment] 2016-01-26 20:58
Here's the output I'm getting now with the new version (switching back to the normal version still works, so this isn't a temporary network issue or anything):

$ sudo npm install -g git+https://github.com/KraigM/homebridge-nest.git#1dbe213cad45d11782ff4870d7c2dc8b0aed6d9e continuation-local-storage
$ homebridge
Loaded plugin: homebridge-nest
Registering platform 'homebridge-nest.Nest'
\-\-\-
Loaded config.json with 0 accessories and 1 platforms.
\-\-\-
Loading 1 platforms...
[Nest Thermostat] Initializing Nest platform...
[Nest Thermostat] Fetching Nest devices.
[Nest Thermostat] [HomeBridgeNestFirebase] User is logged out
[Nest Thermostat] [HomeBridgeNestFirebase] User null is logged in with custom
[Nest Thermostat] [HomeBridgeNestFirebase] Disconnect Detected
[Nest Thermostat] [HomeBridgeNestFirebase] Disconnect Detected
[Nest Thermostat] [HomeBridgeNestFirebase] Disconnect Detected
[Nest Thermostat] [HomeBridgeNestFirebase] Disconnect Detected
[Nest Thermostat] [HomeBridgeNestFirebase] Disconnect Detected
[Nest Thermostat] [HomeBridgeNestFirebase] Disconnect Detected
[Nest Thermostat] [HomeBridgeNestFirebase] Disconnect Detected
[Nest Thermostat] [HomeBridgeNestFirebase] Disconnect Detected
[Nest Thermostat] [HomeBridgeNestFirebase] Disconnect Detected
[Nest Thermostat] [HomeBridgeNestFirebase] Disconnect Detected
[Nest Thermostat] [HomeBridgeNestFirebase] Disconnect Detected

**Comment by KraigM** [comment] 2016-01-27 14:04
OK this time it was FireBase's fault :stuck_out_tongue_winking_eye:, but I throughly tested this one and it works fine for me.
```
npm install -g git+https://github.com/KraigM/homebridge-nest.git#f745a00b35e3ab4e06dc9178121b83833648fa73
```

**Comment by ande2965** [comment] 2016-01-27 14:11
Okay, I'm up and running with the latest version. I'll let you know if/when the error appears again.

$ sudo npm install -g git+https://github.com/KraigM/homebridge-nest.git#f745a00b35e3ab4e06dc9178121b83833648fa73 continuation-local-storage
$ homebridge
Loaded plugin: homebridge-nest
Registering platform 'homebridge-nest.Nest'
\-\-\-
Loaded config.json with 0 accessories and 1 platforms.
\-\-\-
Loading 1 platforms...
[Nest Thermostat] Initializing Nest platform...
[Nest Thermostat] Fetching Nest devices.
[Nest Thermostat] [HomeBridgeNestFirebase] User is logged out
[Nest Thermostat] [HomeBridgeNestFirebase] User null is logged in with custom
[Nest Thermostat] Temperature unit for Upstairs is: Fahrenheit
[Nest Thermostat] Current temperature for Upstairs is: 69 F
[Nest Thermostat] Current heating for Upstairs is: Heating
[Nest Thermostat] Current humidity for Upstairs is: 30%
[Nest Thermostat] Target temperature for Upstairs is: 70 F
[Nest Thermostat] Target heating for Upstairs is: Heating
[Nest Thermostat] Away for Upstairs is: false
[Nest Thermostat] Initializing platform accessory 'Upstairs'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
\<snip\>             
Homebridge is running on port 51829.

**Comment by jclarke0000** [comment] 2016-01-29 00:10
I'm also seeing this issue.  will keep an eye out for the next release.

**Comment by ande2965** [comment] 2016-02-29 14:29
Just a quick update. I haven't seen a reoccurrence of the bug with the version you put out for testing. Looking good so far!

**Comment by KraigM** [comment] 2016-03-01 15:08
Awesome, I will get this merged into a release

**Comment by ande2965** [comment] 2016-03-04 14:13
After all of that time, I finally hit the error again:

[Nest Thermostat] Current temperature for Upstairs is: 66 F
FIREBASE WARNING: auth() was canceled: {"error":"service unavailable","type":"https://developer.nest.com/documentation/cloud/error-messages#service-unavailable","message":"service unavailable","instance":"16dc841c-2877-49ba-8a89-d79897a9459f"} 
[Nest Thermostat] [HomeBridgeNestFirebase] User is logged out

**Comment by jclarke0000** [comment] 2016-03-04 14:24
I had been running 1.0.1 until today and I hadn't seen the error in weeks.  Just updated to 1.0.2 today.  Will report if I see the error again.

**Comment by KraigM** [comment] 2016-03-04 14:28
Its gotta be something on there end

@ande2965 Are there any [Nest Thermostat] logs before or after that?

@jclarke0000 Yeah I haven't done anything in the officially released versions to handle this.  I added a few minor checks and logging to a special version

**Comment by KraigM** [comment] 2016-03-12 18:51
I think I have a solution to the issue.  I figured out a way to force unauth and my solution works.  Basically if you have successfully authorized in the session and you "lose authorization", it will just attempt to reauthorize using the same token over and over until successful (pauses for 5 seconds between attempts).

**Comment by KraigM** [comment] 2016-03-12 19:01
Just released it in version 1.1.0.  If it doesn't fix the issue just comment here and I will reopen (but hopefully all goes well :smile:)

**Closed by KraigM** 2016-03-12 19:01 UTC
Labels: bug

**Comment by jbolter** [comment] 2016-03-12 19:20
Thanks @KraigM !

**Comment by jclarke0000** [comment] 2016-03-12 20:23
Thanks @KraigM. Just upgraded to the new version. Will keep an eye on it.
