### ISSUE TITLE
HomeBridge-Nest Promise is not defined issue

### ISSUE THREAD

**Issue by Dave10950** [KraigM/homebridge-nest#34] opened 2016-01-17 21:32 UTC
Hi, I tried using the old API but I had this Promise is not defined issue, so I tried using the new API, but I get the same issue and no token. Please help. Thank you

Error I get is below;

Loading 1 platforms...
Initializing Nest platform...
Fetching Nest devices.

/usr/local/lib/node_modules/homebridge-nest/index.js:58
	return new Promise(function (resolve, reject) {
	           ^
ReferenceError: Promise is not defined
    at setupConnection (/usr/local/lib/node_modules/homebridge-nest/index.js:58:13)
    at Object.NestPlatform.accessories (/usr/local/lib/node_modules/homebridge-nest/index.js:129:3)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:211:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:205:14)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:35:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Any help is greatly appreciated! thank you.

**Comment by Dave10950** [comment] 2016-01-20 04:38
I was able to narrow it down to the following warning; 

npm WARN EPEERINVALID cls-bluebird@1.0.1 requires a peer of continuation-local-storage@~3 but none was installed.

but I can't figure out what the solution is, thank you

**Comment by KraigM** [comment] 2016-01-20 15:01
It looks like you are missing dependencies. Try: 
```
npm uninstall -g homebridge-nest
npm install -g homebridge-nest
```

**Comment by andrews89** [comment] 2016-01-22 21:41
I am having the same error after a fresh install and an uninstall/reinstall.

Loaded config.json with 0 accessories and 1 platforms.
---
Loading 1 platforms...
[Nest] Initializing Nest platform...
[Nest] Fetching Nest devices.

/usr/local/lib/node_modules/homebridge-nest/index.js:58
        return new Promise(function (resolve, reject) {
                   ^
ReferenceError: Promise is not defined
    at setupConnection (/usr/local/lib/node_modules/homebridge-nest/index.js:58:13)
    at Object.NestPlatform.accessories (/usr/local/lib/node_modules/homebridge-nest/index.js:129:3)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:211:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:205:14)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:35:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
andrews89@zoneminder:~$
[0] 0:bash- 1:bash*                               

I'm not sure where to go from here - Any help is greatly appreciated.

**Comment by KraigM** [comment] 2016-01-23 15:15
Its missing the Promise module in homebridge-nest which is required per the package
```
"promise": "^7.0.4",
```
of course it might be there but it just doesn't have permission to it.  I would check in the directory `/usr/local/lib/node_modules/homebridge-nest/node_modules/` and see if you see a promise folder

**Comment by andrews89** [comment] 2016-01-23 19:46
Yup, you're right - It's there but has no owner assigned to it: 

andrews89@zoneminder:/usr/local/lib/node_modules/homebridge-nest/node_modules$ ls
firebase  inherits  promise  request-promise  unofficial-nest-api
andrews89@zoneminder:/usr/local/lib/node_modules/homebridge-nest/node_modules$ ls -l
total 20
drwxr-xr-x 4 nobody andrews89 4096 Jan 22 15:36 firebase
drwxr-xr-x 2 nobody andrews89 4096 Jan 22 15:36 inherits
drwxr-xr-x 7 nobody andrews89 4096 Jan 22 15:36 promise
drwxr-xr-x 4 nobody andrews89 4096 Jan 22 15:36 request-promise
drwxr-xr-x 3 nobody andrews89 4096 Jan 22 15:36 unofficial-nest-api

What user/group should I switch it to for homebridge to pick it up?  Thank you much for the help!

**Comment by KraigM** [comment] 2016-01-23 22:32
Im guessing it was installed with sudo and ran without sudo?

**Comment by andrews89** [comment] 2016-01-23 23:12
It was installed with sudo as npm throws errors otherwise, but the same error with promise occurs even when homebridge is run with sudo.

**Comment by KraigM** [comment] 2016-01-23 23:28
you could always nuclear approach it with chmod -R 777

**Comment by andrews89** [comment] 2016-01-23 23:38
Strangely it still throws the same error even after opening up the permissions. I even tried 777'ing everything in the folder one step higher up and same error. I'll keep working on this more once I get back home. Thank you again very much for taking the time to help me out with this!

**Comment by andrews89** [comment] 2016-01-24 09:55
Alright, I played a little more with it and got nowhere.  Next step for me was creating a fresh Ubuntu 14.04.3 LTS VM 32bit to test on, so I set that up and fully updated it.  After installing all dependencies listed on the homebridge github (along with nodejs v. 0.10.25 and npm v. 1.3.10, both by using apt), then installing homebridge-nest, I get the exact same error as on my other machine (ReferenceError: Promise is not defined).  Not sure if any of this will help, but considering it was done from a fresh machine following all steps listed over at the homebridge repo and here, it seems to have something to do with the setup.  Let me know what other info you need, and if you want the VDI I'd be happy to share.

**Comment by KraigM** [comment] 2016-01-25 03:13
try:
```
cd /usr/local/lib/node_modules/homebridge-nest/
sudo rm -rf node_modules
npm install
```

**Comment by andrews89** [comment] 2016-01-25 17:15
npm is unhappy if not run under sudo:

andrews89@zoneminder:/usr/local/lib/node_modules/homebridge$ cd /usr/local/lib/node_modules/homebridge-nest/
andrews89@zoneminder:/usr/local/lib/node_modules/homebridge-nest$ sudo rm -rf node_modules
andrews89@zoneminder:/usr/local/lib/node_modules/homebridge-nest$ npm install
npm http GET https://registry.npmjs.org/promise
npm http GET https://registry.npmjs.org/request-promise
npm http GET https://registry.npmjs.org/firebase
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/promise
npm http 304 https://registry.npmjs.org/firebase
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/request-promise
npm ERR! git fetch -a origin (https://github.com/kraigm/unofficial_nodejs_nest.git) error: cannot open FETCH_HEAD: Permission denied
npm ERR! Error: Command failed: error: cannot open FETCH_HEAD: Permission denied
npm ERR!
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:637:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:743:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /usr/local/lib/node_modules/homebridge-nest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code 1
npm ERR! Error: EACCES, open 'npm-debug.log'
npm ERR!  { [Error: EACCES, open 'npm-debug.log'] errno: 3, code: 'EACCES', path: 'npm-debug.log' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.16.0-57-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /usr/local/lib/node_modules/homebridge-nest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path npm-debug.log
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open 'npm-debug.log'
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/lib/node_modules/homebridge-nest/npm-debug.log
npm ERR! not ok code 0


But when run with sudo it executes alright with warnings: 

andrews89@zoneminder:/usr/local/lib/node_modules/homebridge-nest$ sudo npm install
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/firebase
npm http GET https://registry.npmjs.org/request-promise
npm http GET https://registry.npmjs.org/promise
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/request-promise
npm http 304 https://registry.npmjs.org/promise
npm http 304 https://registry.npmjs.org/firebase
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/bluebird
npm http GET https://registry.npmjs.org/cls-bluebird
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/asap
npm http GET https://registry.npmjs.org/faye-websocket/-/faye-websocket-0.9.3.tgz
npm http 304 https://registry.npmjs.org/cls-bluebird
npm http 304 https://registry.npmjs.org/bluebird
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/asap
npm http 200 https://registry.npmjs.org/faye-websocket/-/faye-websocket-0.9.3.tgz
npm http GET https://registry.npmjs.org/shimmer
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/bl
npm http GET https://registry.npmjs.org/caseless
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/shimmer
npm http GET https://registry.npmjs.org/stringstream
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/isstream
npm http GET https://registry.npmjs.org/is-typedarray
npm http GET https://registry.npmjs.org/har-validator
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/continuation-local-storage
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/caseless
npm http 304 https://registry.npmjs.org/forever-agent
npm http 304 https://registry.npmjs.org/bl
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/websocket-driver/-/websocket-driver-0.5.2.tgz
npm http 304 https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/stringstream
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/isstream
npm http 304 https://registry.npmjs.org/is-typedarray
npm http 304 https://registry.npmjs.org/har-validator
npm http 304 https://registry.npmjs.org/continuation-local-storage
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm http 200 https://registry.npmjs.org/websocket-driver/-/websocket-driver-0.5.2.tgz
npm http GET https://registry.npmjs.org/delayed-stream
npm http GET https://registry.npmjs.org/mime-db
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/delayed-stream
npm http 304 https://registry.npmjs.org/mime-db
npm http GET https://registry.npmjs.org/assert-plus
npm http GET https://registry.npmjs.org/jsprim
npm http GET https://registry.npmjs.org/sshpk
npm http 304 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/is-my-json-valid
npm http GET https://registry.npmjs.org/pinkie-promise
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/pinkie-promise
npm http 304 https://registry.npmjs.org/assert-plus
npm http 304 https://registry.npmjs.org/jsprim
npm http 304 https://registry.npmjs.org/sshpk
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/is-my-json-valid
npm http GET https://registry.npmjs.org/async-listener
npm http GET https://registry.npmjs.org/emitter-listener
npm http GET https://registry.npmjs.org/pinkie
npm http GET https://registry.npmjs.org/verror/1.3.6
npm http GET https://registry.npmjs.org/extsprintf/1.0.2
npm http GET https://registry.npmjs.org/json-schema/0.2.2
npm http GET https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/supports-color
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/graceful-readlink
npm http 304 https://registry.npmjs.org/async-listener
npm http 304 https://registry.npmjs.org/emitter-listener
npm http 304 https://registry.npmjs.org/json-schema/0.2.2
npm http 304 https://registry.npmjs.org/has-ansi
npm http 304 https://registry.npmjs.org/pinkie
npm http 304 https://registry.npmjs.org/verror/1.3.6
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/extsprintf/1.0.2
npm http 304 https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/escape-string-regexp
npm http 304 https://registry.npmjs.org/graceful-readlink
npm http GET https://registry.npmjs.org/util-deprecate
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/process-nextick-args
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/shimmer/1.0.0
npm http GET https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/util-deprecate
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/process-nextick-args
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/shimmer/1.0.0
npm http 304 https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/dashdash
npm http GET https://registry.npmjs.org/jsbn
npm http GET https://registry.npmjs.org/tweetnacl
npm http GET https://registry.npmjs.org/jodid25519
npm http GET https://registry.npmjs.org/ecc-jsbn
npm http GET https://registry.npmjs.org/asn1
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/jsbn
npm http 304 https://registry.npmjs.org/dashdash
npm http 304 https://registry.npmjs.org/tweetnacl
npm http 304 https://registry.npmjs.org/jodid25519
npm http GET https://registry.npmjs.org/generate-function
npm http 304 https://registry.npmjs.org/ecc-jsbn
npm http GET https://registry.npmjs.org/generate-object-property
npm http GET https://registry.npmjs.org/xtend
npm http GET https://registry.npmjs.org/jsonpointer/2.0.0
npm http 304 https://registry.npmjs.org/asn1
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/generate-function
npm http 304 https://registry.npmjs.org/generate-object-property
npm http 304 https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/jsonpointer/2.0.0
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm http GET https://registry.npmjs.org/is-property
npm http GET https://registry.npmjs.org/websocket-extensions/-/websocket-extensions-0.1.1.tgz
npm http 304 https://registry.npmjs.org/is-property
npm http 200 https://registry.npmjs.org/websocket-extensions/-/websocket-extensions-0.1.1.tgz
inherits@2.0.1 node_modules/inherits

unofficial-nest-api@0.1.4 node_modules/unofficial-nest-api

promise@7.1.1 node_modules/promise
└── asap@2.0.3

firebase@2.4.0 node_modules/firebase
└── faye-websocket@0.9.3 (websocket-driver@0.5.2)

request-promise@1.0.2 node_modules/request-promise
├── bluebird@2.10.2
├── continuation-local-storage@3.1.4 (emitter-listener@1.0.1, async-listener@0.5.6)
├── cls-bluebird@1.0.1 (shimmer@1.1.0)
├── request@2.67.0 (is-typedarray@1.0.0, aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, tunnel-agent@0.4.2, oauth-sign@0.8.0, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.7, qs@5.2.0, combined-stream@1.0.5, tough-cookie@2.2.1, form-data@1.0.0-rc3, mime-types@2.1.9, bl@1.0.1, http-signature@1.1.0, hawk@3.1.3, har-validator@2.0.6)
└── lodash@3.10.1
andrews89@zoneminder:/usr/local/lib/node_modules/homebridge-nest$


Sorry for the log dump, just wanted to include everything.  The only warnings are in relation to the nodejs version - would that be the issue?  nodejs was installed via apt repo - would it help to try to install/build manually?

**Comment by Xtropy74** [comment] 2016-01-25 19:34
Having the same problem. Just upgraded to the latest homebridge-nest and getting the exact same errors as Andrews. Tried all the suggestions in this thread and it doesn't fix the issue. All errors are related to "promise". Worked perfectly fine in the previous release....

**Comment by Xtropy74** [comment] 2016-01-25 20:03
If I do the following steps, it works perfect again:

sudo npm -g uninstall homebridge-nest
sudo npm -g install homebridge-nest@0.1.1

If I install anything above that version, I get the same errors. Looks like I'll be sticking with 0.1.1 for now, no issues

**Comment by andrews89** [comment] 2016-01-25 20:37
Thank you Xtropy! It now works!

Unrelated question though-how do I get it to display in Fahrenheit?  Homebridge's console output shows the temperature unit is Fahrenheit, but it's showing a Celsius value.

**Comment by KraigM** [comment] 2016-01-26 14:01
What version of node are you guys using?

**Comment by KraigM** [comment] 2016-01-26 14:03
Actually I found it in your logs. You are on 0.10. Upgrade to at least 0.12.x. I use 0.12.8

**Comment by Xtropy74** [comment] 2016-01-26 15:10
I did the following:

sudo npm cache clean -f
sudo npm install -g n
sudo npm n 0.12.8
sudo npm -g uninstall homebridge-nest
sudo npm -g install homebridge-nest

When I run node -v I get an output of v0.12.8

When I start Homebridge now, I get a crash with the following details:

Starting Homebridge
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns
/lib/dns_sd.js:35
    throw ex;
          ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/h
ap-nodejs/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

I rolled back with the following commands and everything works again:

sudo npm cache clean -f
sudo npm n 0.10.25
sudo npm -g uninstall homebridge-nest
sudo npm -g install homebridge-nest@0.1.1

**Comment by KraigM** [comment] 2016-01-26 15:11
Its because you have to rebuild all the things, Im guessing

**Comment by Xtropy74** [comment] 2016-01-26 15:14
I'll stick with 0.1.1. It's working fine. It's a lot of work just to get this upgraded for one device and no guarantees this will fix the issue we're experiencing.

**Comment by KraigM** [comment] 2016-01-26 15:31
0.1.1 has a lot of issues bc it is on the unofficial api.  Nest has a lot of flip outs when you use the unofficial api and who knows when they might kill it off entirely.

**Comment by KraigM** [comment] 2016-01-26 15:32
Its not official so they can kill it whenever they want and no one can really say anything about it

**Comment by KraigM** [comment] 2016-01-26 15:37
Just repeat what you did above but this time throw in a 

```
sudo npm -g uninstall homebridge
sudo npm -g install homebridge
```

**Comment by Xtropy74** [comment] 2016-01-26 15:51
Well that worked. Here are the commands I ran

sudo npm cache clean -f
sudo npm install -g n
sudo n 0.12.8
sudo npm -g uninstall homebridge-nest
sudo npm -g install homebridge-nest
sudo npm -g uninstall homebridge
sudo npm -g install homebridge

Unfortunately I cannot authenticate but the legacy API is working. I think the issue is the "PIN Code" I have it listed as "PIN CODE". I followed your instructions to use the new API and have the "token", "clientID" and "clientSecret" after creating my DEV account but for code I just have "Pin Code". The instructions you gave to get it were different than whats on the website.

I can just use the legacy API for now until I figure this out. Thanks for the help BTW

**Comment by Xtropy74** [comment] 2016-01-26 16:05
Figured it out. I misunderstood that step 12 meant "Open the Authorization URL in your web browser". Also got confused about the "token" wording but figured it out. All is working now and using the new API. Thanks yet again for the guidance in resolving this

**Comment by andrews89** [comment] 2016-01-26 18:56
That solved all of my problems as well.  Thank you Xtropy for showing how you solved this!  And thank you KraigM for helping us!

**Comment by KraigM** [comment] 2016-03-01 16:32
Sounds like this is resolved? Im going to go ahead and close this for now but feel free to follow up

**Closed by KraigM** 2016-03-01 16:32 UTC
Labels: help wanted
