### ISSUE TITLE
Siri won't give temperature in celsius

### ISSUE THREAD

**Issue by redec** [KraigM/homebridge-nest#35] opened 2016-01-18 21:01 UTC
My nest is configured for celsius, the iphone region is configured to be Canada...whenever I talk to siri about outside temperatures she always talks in celsius, The Insteon+ app even shows the temp in celsius....*only* when accessing my nest through siri she gives me fahrenheit, and I can't seem to fix it.  

I noticed something else a little odd (not sure if it's related), when I switch my nest back and forth from celsius to fahrenheit I see this in the log:
Temperature unit for Home is: Fahrenheit
Temperature unit for Home is: 0
Temperature unit for Home is: Fahrenheit
Temperature unit for Home is: 0
Looking at the code it really doesn't look like this output should really be possible...

**Comment by KraigM** [comment] 2016-01-23 15:21
hmm not sure.  The are you using the new api?  And what version are you using?  Those logs look old.

**Comment by eyv** [comment] 2016-01-24 00:56
I've experienced the same issue. Siri will correctly set the temperature in Celsius if told to set the temperature, but will only answer in Fahrenheit if I ask what temperature Nest is reporting, even though Nest is set to Celsius.

**Comment by redec** [comment] 2016-01-24 05:08
Yes, it is using the new API...running homebridge-nest v1.0.1 with homebridge v0.2.15.

**Comment by redec** [comment] 2016-01-24 23:19
Well, I don't have an explanation for it, but I can no longer reproduce this.  I was beginning to debug it and then it started working properly.  I didn't fix/change anything other than I updated to the latest release of homebridge-wink, which I wouldn't expect should affect this.  The logging weirdness was not related and is just a small bug which I've fixed in pull request #38

**Comment by KraigM** [comment] 2016-01-25 02:52
Is your nest hooked up to wink as well?

**Comment by redec** [comment] 2016-01-25 03:46
It is hooked up to the wink hub, yes...however I have it ignored in the config of homebridge-wink

**Comment by KraigM** [comment] 2016-02-11 15:13
The only thing I can think of is that wink had a bug that was still somehow exposing your nest.  

@eyv Are you experiencing the issue still?  Can you make sure your plugins are up to date?

**Comment by eyv** [comment] 2016-02-12 03:23
OK, gimme a few days please. Thanks!

**Comment by eyv** [comment] 2016-02-12 03:36
Yes, I'm still seeing this with all the updated packages. The console output is in Celsius, but Siri gives it to me in Fahrenheit. :(

**Comment by KraigM** [comment] 2016-02-26 19:38
I merged #38 into 1.0.2 so the logs should be nicer now.

@eyv can you update to 1.0.2 and send a spit out of the logs and as well as a screenshot of siri giving you F instead of C, please :smile:

**Comment by eyv** [comment] 2016-02-27 00:21
$ sudo npm -g update; npm -g update homebridge homebridge-nest
/usr/bin/node-gyp -> /usr/lib/node_modules/node-gyp/bin/node-gyp.js
- assert-plus@0.2.0 node_modules/homebridge-nest/node_modules/sshpk/node_modules/assert-plus
- lodash._basetostring@3.0.1 node_modules/node-gyp/node_modules/lodash._basetostring
- lodash._createpadding@3.6.1 node_modules/node-gyp/node_modules/lodash._createpadding
- lodash.padleft@3.1.1 node_modules/node-gyp/node_modules/lodash.padleft
- lodash.padright@3.1.1 node_modules/node-gyp/node_modules/lodash.padright
/usr/lib
├── homebridge-nest@1.0.2
└── node-gyp@3.3.0

$ homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
Loaded plugin: homebridge-ifttt
Registering platform 'homebridge-ifttt.IFTTT'
---
Loaded plugin: homebridge-legacy-plugins
Registering accessory 'homebridge-legacy-plugins.AD2USB'
Registering accessory 'homebridge-legacy-plugins.Carwings'
Registering accessory 'homebridge-legacy-plugins.ELKM1'
Registering accessory 'homebridge-legacy-plugins.FileSensor'
Registering accessory 'homebridge-legacy-plugins.GenericRS232Device'
Registering accessory 'homebridge-legacy-plugins.HomeMatic'
Registering accessory 'homebridge-legacy-plugins.HomeMaticThermo'
Registering accessory 'homebridge-legacy-plugins.HomeMaticWindow'
Registering accessory 'homebridge-legacy-plugins.HttpGarageDoorOpener'
Registering accessory 'homebridge-legacy-plugins.HttpHygrometer'
Registering accessory 'homebridge-legacy-plugins.HttpThermometer'
Registering accessory 'homebridge-legacy-plugins.Tesla'
Registering accessory 'homebridge-legacy-plugins.X10'
Registering accessory 'homebridge-legacy-plugins.mpdclient'
Registering platform 'homebridge-legacy-plugins.Domoticz'
Registering platform 'homebridge-legacy-plugins.HomeAssistant'
Registering platform 'homebridge-legacy-plugins.HomeSeer'
Registering platform 'homebridge-legacy-plugins.ISY'
Registering platform 'homebridge-legacy-plugins.LIFx'
Registering platform 'homebridge-legacy-plugins.SmartThings'
Registering platform 'homebridge-legacy-plugins.TelldusLive'
Registering platform 'homebridge-legacy-plugins.ZWayServer'
---
Loaded plugin: homebridge-nest
Registering platform 'homebridge-nest.Nest'
---
Loaded plugin: homebridge-philipshue
Registering platform 'homebridge-philipshue.PhilipsHue'
---
Loaded config.json with 0 accessories and 4 platforms.
---
Loading 4 platforms...
[IFTTT] Initializing IFTTT platform...
[IFTTT] Loading accessories...
[Thermostat] Initializing Nest platform...
[Thermostat] Fetching Nest devices.
[Lights] Initializing PhilipsHue platform...
[Lights] PhilipsHue Platform Plugin Version 0.0.2
[Lights] Fetching Philips Hue lights...
[SmartThings] Initializing SmartThings platform...
Loading legacy platform SmartThings
[SmartThings] Fetching SmartThings devices...
[Lights] Initializing platform accessory [redacted]...
[Lights] Initializing platform accessory [redacted]...
[Lights] Initializing platform accessory [redacted]...
[Lights] Initializing platform accessory [redacted]...
[Lights] Initializing platform accessory [redacted]...
[SmartThings] Initializing platform accessory [redacted]...
[SmartThings] Loaded services for [redacted]
[SmartThings] Initializing platform accessory [redacted]...
[SmartThings] Loaded services for [redacted]
...
[Thermostat] Current temperature for Upstairs is: 19.5 C
[Thermostat] Current humidity for Upstairs is: 35%
[Thermostat] Target temperature for Upstairs is: 18 C
[Thermostat] Target heating for Upstairs is: Heating
[Thermostat] Initializing platform accessory 'Upstairs'...

![img_6001](https://cloud.githubusercontent.com/assets/101942/13369005/b9c9d140-dcb5-11e5-88e3-f60b208971a8.PNG)

**Comment by KraigM** [comment] 2016-03-01 15:24
@eyv what is between:
```
[SmartThings] Loaded services for [redacted]
...
[Thermostat] Current temperature for Upstairs is: 19.5 C
```

because I am not seeing the line that says 

```
[Thermostat] Temperature unit for Upstairs is: Celsius
```

**Comment by KraigM** [comment] 2016-03-01 15:25
@eyv Also can you include a screenshot of the thermostat details on Insteon+ (where it shows its on celsius and not fahrenheit).

**Comment by KraigM** [comment] 2016-03-01 15:26
@eyv When this happens, will siri always use fahrenheit for the duration of the homebridge session or will it go back and forth?

**Comment by eyv** [comment] 2016-03-01 15:28
OK, I'll get on that. What about the line about temperature unit. Let's assume it doesn't naturally show up. Any idea why it would not? Is there perhaps a setting in the config I'm missing?

**Comment by eyv** [comment] 2016-03-01 15:30
I've never heard Siri use F to report thermostat temps. "She" does set them correctly when I call them out without units -- sets it in C and not F. Especially when the told to make it 19 :)

**Comment by KraigM** [comment] 2016-03-01 16:18
@eyv So I think I figured out why it is not showing up in the logs.  It only logs when the value changes and all values start at 0 which for temp means celsius.  Now whether or not that it has bearing or is just a red herring, idk.

Given that I have another thing to try as well. Since the temp unit is live updated, if you change it to F and change it back to C then it might send Siri the correct signal so that Siri will respond in C. Try this:
- Run homebridge
- Change your temp units to F in the Nest app
- Wait for the homebridge logs to show up similar to
```
[Thermostat] Temperature unit for Nest is: Fahrenheit
[Thermostat] Current temperature for Nest is: 69 F
[Thermostat] Target temperature for Nest is: 67 F
```

- Change your temp units to C in the Nest app
- Wait for the logs to show up similar to

```
[Thermostat] Temperature unit for Nest is: Celsius
[Thermostat] Current temperature for Nest is: 20.5 C
[Thermostat] Target temperature for Nest is: 19 C
```
- Retest siri and see if you get the correct responses

If that seems to fix the issue completing, then I can prob figure out what the issue is or at least make a work around for it.

**Comment by KraigM** [comment] 2016-03-01 16:18
@eyv One other thing, what version of homebridge are you using?

**Comment by eyv** [comment] 2016-03-01 23:34
@KraigM , thanks for the time you're putting into this!

/usr/lib
└─┬ homebridge@0.2.19
  └─┬ hap-nodejs@0.2.5
    ├── curve25519@1.1.0  (git://github.com/KhaosT/node-curve25519.git#922eae612bb379fa84e8deb29f80c53d57c8be7b)
    ├── ed25519@0.0.3  (git://github.com/KhaosT/ed25519.git#6356bc9e6e4643d56020293c14920ac12bcaa1ac)
    ├── mdns@2.2.11  (git://github.com/KhaosT/node_mdns.git#8ff4d603197a92c3cc829ddd37ddfac5bfe21332)
    └── srp@0.2.0  (git://github.com/KhaosT/node-srp.git#7feff53254897a0b1b9f0667ad17a8beb78acbb9)

/usr/lib
├── continuation-local-storage@3.1.6
└─┬ homebridge-nest@1.0.2
  └── unofficial-nest-api@0.1.4  (git+https://github.com/kraigm/unofficial_nodejs_nest.git#3cbd337adc32fab3b481659b38d86f9fcd6a9c02)

![img_6003](https://cloud.githubusercontent.com/assets/101942/13445761/da25e14c-dfd3-11e5-8286-e5436f786161.PNG)


[Thermostat] Temperature unit for Upstairs is: Fahrenheit
[Thermostat] Current temperature for Upstairs is: 65 F
[Thermostat] Target temperature for Upstairs is: 64 F
[Thermostat] Current temperature for Upstairs is: 66 F
[Thermostat] Temperature unit for Upstairs is: Celsius
[Thermostat] Current temperature for Upstairs is: 18.5 C
[Thermostat] Target temperature for Upstairs is: 18 C

No joy -- still reporting 64.4 :(

**Comment by luisiam** [comment] 2016-03-07 17:15
I am not 100% sure about this but if you change the region of your iPhone to somewhere which use C primarily (i.e. somewhere in Asia), Siri should be reporting the temp in C.

**Comment by eyv** [comment] 2016-03-07 17:16
Well, yes, of course, but is this a debugging question or a "solution"? Because as a solution, it leaves much to be desired :)

Thus spake luisiam on Monday Mar 07 2016 11:15:07:

**Comment by luisiam** [comment] 2016-03-07 17:22
I will not be surprised if that's the way Apple set up everything. I still remember I cannot get my iPad to display weather in C (in the notification center and calendar) unless I change the region.

**Comment by eyv** [comment] 2016-03-07 17:24
OK, so does this mean we can't keep troubleshooting / trying to fix this? Thanks either way!

**Comment by KraigM** [comment] 2016-03-07 17:26
@eyv does changing your region work?

**Comment by eyv** [comment] 2016-03-08 01:02
Yes, it does. When setting a region which uses Celsius (every civilized place on earth :), Siri reports temperatures in Celsius.

**Comment by luisiam** [comment] 2016-03-08 01:04
I would say that's something to do with Apple iOS. We can do nothing on the HomeBridge/plugin side. I may be wrong.

**Comment by eyv** [comment] 2016-03-08 01:05
:'(

**Comment by KraigM** [comment] 2016-03-11 15:25
Since this particular issue seems to be out of our hands, I'm going to close this

**Closed by KraigM** 2016-03-11 15:25 UTC
