### ISSUE TITLE
potential for increased battery drain?

### ISSUE THREAD

**Issue by spmcewen** [KraigM/homebridge-nest#18] opened 2015-12-31 13:31 UTC
My Nest doesn't have a dedicated C wire for power but for the past 2 years I have never had an issue with the battery draining.  A couple days ago I set up a the Lutron Smart Hub and a wireless in wall switch with HomeKit.  I also set up Homebridge with the Nest plugin using the newer token based API.  Everything worked great with Siri and HomeKit scenes.  However, yesterday my Nest went into low power mode and disabled wifi and the motion sensor.  The battery was reading around 3.6v.  Being winter in New England this isn't something to mess around with so I immediately shut down Homebridge and removed all the Nest HomeKit configuration.  This morning the battery is back up to 3.8v.

Does Homebridge and the Nest plugin increase the frequency that the Nest checks for temperature changes?   This is the only explanation I can think of. It seems too strange that I never had battery issues until I set up HomeKit/Homebridge, and it went away when I turned it off.  Is there anything else  that Homebridge could be doing that could inadvertently be causing additional battery drain?

**Comment by KraigM** [comment] 2015-12-31 19:02
I have noticed that the unofficial API does weird things to Nest.  Yesterday I officially released a new version of the plugin that supports the official Nest API.  I would suggest trying that and see if it helps.  For more info, see the [main page](https://github.com/KraigM/homebridge-nest)

**Comment by KraigM** [comment] 2015-12-31 19:14
With the old api, we used a subscribe system that would keep an open http request at all times but since it is a normal connection it has to be finished and reopened every minute to maintain. Even though it was a connection to their servers, I think the servers made a similar connection to the Nest directly.  I have even seen it screw up its connection to the main app.

The new API uses a completely different technology and is the one Nest approved of enough to open up.  It still maintains a connection, but this time the connection uses a new web socket technology.  

Now before, your Nest may have only been updating the servers when you opened up the Nest app and now it may have to keep updating it so it can keep updating HomeBridge and thus HomeKit.  Therefore you still may see the drain. But given that I haven't had the weird connection issues since I switched to the new API, it is also hopefully not going to hit the Nest as hard.

**Comment by KraigM** [comment] 2015-12-31 19:16
If you continue to have the issue after updating and switching to the new API, let me know.  We could potentially create a configuration that tells it to only update every once in a while or maybe even only when asked.  But you will prob have some usability problems then, and triggers might not work either

**Comment by spmcewen** [comment] 2016-01-01 14:30
Thank you for the explanation.  In my original report above I missed the detail that I was originally using the version that used the unofficial API. I changed to the branch that used the new token based API after homebridge crashed.  It was shortly after that when I noticed the battery drain - so it's hard to say which version actually caused the battery problem.  Now that I understand the issue a little better I'll try again with the latest release and see if that causes problems again.

**Comment by spmcewen** [comment] 2016-01-02 00:12
I'm starting to think that it was the old API causing the battery drain.  This morning I updated to the latest version using the official API and my Nest battery has been at 3.8+ volts all day.  This is excellent, thanks for creating this plugin and making this work the way they should!

**Comment by fahrvergnuugen** [comment] 2016-01-04 13:43
@spmcewen on a side note - do yourself a favor and install a C wire!

My nest ruined two relay boards on two different furnaces in two different houses because I wasn't running a C wire. In order to charge itself, it rapidly "chatters" the relay on then off to generate current through the thermostat wires - this was really pronounced in my installation because I very rarely use my furnace. This chattering causes the relays to prematurely fail, and in my case it cost $100 to replace!

**Comment by spmcewen** [comment] 2016-01-04 15:19
@fahrvergnuugen That's interesting!  I knew about the quick pulsing it does to charge but this is the first I heard about it causing problems. How long did it take for your relay boards to fail with the nest connected?  Mine has been going on 2+ years now and I haven't had any issues yet. I thought about pulling a new wire for the C connection when I installed the nest, maybe this will prompt me to actually do it.  My thermostat is in a tricky location, but I could replace the wire entirely and put the thermostat in a different room which would probably be a good thing to do anyway.

**Comment by fahrvergnuugen** [comment] 2016-01-04 15:26
@spmcewen It took about 2 years in my old house and about 6 months in the new house. I moved in the late spring and immediately hooked the nest up in the new house. I tested the furnace and it worked fine. 

When I went to use the heat in the fall, the relay was bad. I thought it was strange because I tested the furnace before and it worked fine, then the relay mysteriously failed over the summertime  - that's how I determined the cause and linked it with the relay failure at my old house.

**Comment by pedroserano** [comment] 2016-01-08 15:51
Nest Thermostats Are Having Battery Problems and There's No Fix Yet 

http://gizmodo.com/nest-thermostats-are-having-battery-problems-and-theres-1751800309

**Comment by spmcewen** [comment] 2016-01-08 20:06
I really wish Nest would stop auto updating software that had previously worked perfectly fine.  Living in New England in the Winter and seeing the thermostat go into update mode on a below zero night is pretty concerning.  I wonder if there is a connection here with the fact Nest is based in Palo Alto CA where they see only a handful of days below freezing each year.  There's a huge difference between having home heating be a necessity and just and inconvenience if it's not working.

**Comment by KraigM** [comment] 2016-01-23 15:38
Closing this issue as it seems to be a Nest issue.  Feel free to reopen if it turns out otherwise

**Closed by KraigM** 2016-01-23 15:38 UTC
