### ISSUE TITLE
Siri only adjusts AC not heat

### ISSUE THREAD

**Issue by johntdyer** [KraigM/homebridge-nest#36] opened 2016-01-19 04:52 UTC
I seem to only be able to set the "cooling" temperature but not the heat.  I assume this is simply me issuing the wrong command.  I have tried "

* Siri turn up heat in living room to 70 degrees
* Siri set living room to 70 degrees

but both set the "cooling" temperature but not the heat.  What am I doing wrong ?

**Comment by KraigM** [comment] 2016-01-23 15:16
Do you have it in "range" mode (aka heat-cool)?

**Comment by johntdyer** [comment] 2016-01-23 15:27
I think so

**Comment by KraigM** [comment] 2016-01-23 15:33
Siri only understands one temp, so Nest's two temperature setting had to be handled a little diff. It used to not allow you to change it at all but I added some code that allows you to change whatever temperature is closer to the current temperature. In other words, if the range you set is 67 - 72 and it is currently 75, it will show and allow you to adjust the high temp, but if it was 68, it will show and allow you to adjust the low temp.

**Comment by KraigM** [comment] 2016-01-23 15:50
Duplicate of #14

**Comment by KraigM** [comment] 2016-03-01 16:31
#14 has been resolved so hopefully that helps you.  Im going to close this for now but feel free to follow up

**Closed by KraigM** 2016-03-01 16:31 UTC
Labels: duplicate, help wanted
