### ISSUE TITLE
Can this plugin include support for Nest Protect Smoke Alarms

### ISSUE THREAD

**Issue by Kraiggers** [KraigM/homebridge-nest#33] opened 2016-01-16 14:10 UTC
Hello! First off, I recently found out about Homebridge, and it is quite fantastic, so many thanks to KraigM and all who have contributed.

I have Homebridge and the Nest plugin installed on my mac, and loaded in Launchctl to boot. I am using the new API successfully, and I see both Homebridge and my (one) Nest in the Insteon+ app and in Matthias Hochgatterer's Home app with no problems. I can use the device in the apps to control the Nest, as well as using Siri to interrogate and set temperatures. So, all of that seems to be working just as intended!  AWESOME. 

Is it possible to add the ability to control - or just access the sensor data - from the Nest Protect smoke alarms?  I don't know what this would entail, so forgive the question of it is a dumb request...

Thanks again!

**Comment by Kraiggers** [comment] 2016-01-16 14:13
The Nest developer page says that the Nest API exposes the following information from the Protect Alarms:

View CO or smoke status
View battery health state
View last manual test status and timestamp for last manual test
View online status and last connection information

**Comment by brandwe** [comment] 2016-01-16 18:21
Unfortunately I don't think HomeKit allows for those to be read by Siri. The types seem pretty restrictive: https://developer.apple.com/library/prerelease/watchos/documentation/HomeKit/Reference/HMService_Class/index.html#//apple_ref/doc/constant_group/Accessory_Service_Types

```
NSString *const HMServiceTypeLightbulb;
NSString *const HMServiceTypeSwitch;
NSString *const HMServiceTypeThermostat;
NSString *const HMServiceTypeGarageDoorOpener;
NSString *const HMServiceTypeAccessoryInformation;
NSString *const HMServiceTypeFan;
NSString *const HMServiceTypeOutlet;
NSString *const HMServiceTypeLockMechanism;
NSString *const HMServiceTypeLockManagement;
```

**Comment by KraigM** [comment] 2016-01-16 18:27
Yeah as @brandwe said, not right now.  It _may_ already be possible but unfortunately unless someone is able to dig in and find some things that Apple hasn't announced yet, then there is not much we can do.  

We have a similar situation with Away status.  Technically with that one we already know HomeKit supports it to some degree but we don't have the codes so we had to make up a code and thus it doesn't integrate well (it works, just not well).  

I think for an entirely new device, like NestProtect, we prob should wait until Apple opens something at least close.  Otherwise everything on it would have to be custom.

**Comment by Kraiggers** [comment] 2016-01-19 18:02
Ahh.  Well, I didn't realize the Protect would require un-announced HomeKit compatabilities.  Fingers crossed for a future device Smoke Alarm device.  Or something close.

As an aside, do you gents happen to have any knowledge or insight on why Nest doesn't use the Protect devices as external temperature sensors for Nest?  Presumably they could do so similar to what EcoBee does with their external sensors...?

Thanks for the replies.  Much appreciated!

**Comment by brandwe** [comment] 2016-01-19 18:21
Not related to the product, but my opinion is Nest has fallen behind the other thermostats in functionality, but not design :-)

**Comment by Kraiggers** [comment] 2016-01-19 18:54
Yes, I agree.  However, IMO that isn't necessarily a bad thing, in many cases.  (I just purchased and installed the new 3rd gen Nest after getting the plugin working with my 1st gen.)

The Ecobee3 is quite nice looking, but not only do I not need the complexity it offers, I don't really want it; it exposes to much to the user.  It does work with Homekit, but thanks to this plug-in, so does Nest!  :)

The Nest build quality is superb.  It feels like the iPhone of thermostats (compliment) - dense and solid with exquisitely tight but smooth rotation.  Very impressive.  

I actually think Nest is an excellent piece of design in terms of hiding a lot of complexity that users don't need and are better off without.  Homekit compatibility is an unfortunate victim of the platform battle between Google and Nest.  I'm certain that the Nest (3) would be compatible if Nest was still independent.  Sadly, not the case.  Frankly, I don't think Nest fits very well in the Google family or worldview, but that's just my opinion.

What I find more perplexing is Nest's lack of using the Protect in more creative ways.  They've had it on the market for plenty of time now to roll out more than just the motion sensor assistance.  Seems like a huge missed opportunity (at least so far)...

**Comment by pedroserano** [comment] 2016-01-25 03:00
+1 on keeping an eye on adding Nest Protects, since I own several. 

I'm wondering if there's anything to be gleaned from FirstAlert's homekit-enabled fire alarm? idk, and maybe not because Apple could have easily given them proprietary access to as-yet unannounced homekit service types, or maybe they just created their own custom service types?

http://www.theverge.com/2015/11/12/9724984/first-alert-onelink-smart-smoke-alarm-carbon-monoxide-detector-homekit

**Comment by KraigM** [comment] 2016-03-12 18:08
Added support for SmokeDetected, CarbonMonoxideDetected, and StatusLowBattery

**Comment by KraigM** [comment] 2016-03-12 18:09
Completed and will be in next release (1.1.0)

**Closed by KraigM** 2016-03-12 18:09 UTC
Labels: enhancement

**Comment by Kraiggers** [comment] 2016-03-16 12:41
Awesome. Just updated.  I have six protects - should they show up as individual devices to then be added to rooms?

**Comment by KraigM** [comment] 2016-03-16 13:17
Yes

**Comment by Kraiggers** [comment] 2016-03-16 22:47
Well, I updated Homebridge, and Homebridge-Nest, but I sure as shootin' can't seem to get my Protects to show up. Is there another step I'm missing?  Something in the config file perhaps?

**Comment by KraigM** [comment] 2016-03-16 23:21
permissions?

**Comment by KraigM** [comment] 2016-03-16 23:24
I think I may have only posted this on #slack (and I updated the install steps) but in order to use the new devices you have to add (if not added already) the two permissions:

```
Enable Smoke+CO alarm with read v4 (if you ever might want Nest Protect)
Enable Camera with read v2 (if you ever might want Nest Cam, motion detection only)
```

**Comment by Kraiggers** [comment] 2016-03-17 02:46
Permissions got it, thx.

**Comment by emdoc12** [comment] 2016-06-16 05:19
Just got this setup and running and it is showing both smoke and carbon monoxide as being detected. Both the smartthings app as well as the Nest app both show everything as being all clear.

**Comment by Dero99** [comment] 2017-02-06 17:08
Protect is registered, but not listed under my HomeKit Apps, Nest temp is displayed correctly .  The permissions are setup.  Not sure what the problem is?

>snip<
[Nest] Software version for Hallway Thermostat (Upstairs) is: 5.6-7
[2/6/2017, 8:07:54 AM] [Nest] Current temperature for Hallway Thermostat (Upstairs) is: 18.5 C
[2/6/2017, 8:07:54 AM] [Nest] Current humidity for Hallway Thermostat (Upstairs) is: 35%
[2/6/2017, 8:07:54 AM] [Nest] Target temperature for Hallway Thermostat (Upstairs) is: 18 C
[2/6/2017, 8:07:54 AM] [Nest] Target heating for Hallway Thermostat (Upstairs) is: Heating
[2/6/2017, 8:07:54 AM] [Nest] Away for Hallway Thermostat (Upstairs) is: 1
[2/6/2017, 8:07:54 AM] [Nest] Software version for Hallway Nest Protect is: 3.1rc9
[2/6/2017, 8:07:54 AM] [Nest] Initializing platform accessory 'Hallway Thermostat (Upstairs)'...
[2/6/2017, 8:07:54 AM] [Nest] Initializing platform accessory 'Hallway Nest Protect'...
